### ISSUE TITLE
Assignment 2-Prime Number Checker

### ISSUE THREAD

**Issue by 45bit23** [vtcbca/basic-programming-60bit23#2]
What do you mean by Prime Number ?

**Comment by 60bit23** [comment]
A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself.

**Comment by 45bit23** [comment]
How to check prime numbers?

**Comment by 60bit23** [comment]
To check if a number is prime or not, you can follow these steps
1. Find the factors of the given number and list them.
2. Check the total number of factors of that number.
3. If the number has just two factors (1 and the number itself), then it is a prime number.
4. If it has more than two factors, then it is a composite number.

**Comment by 45bit23** [comment]
Oh... Now I under Stand  how to check prime number.

**Comment by 45bit23** [comment]
How i can check number is prime or not in c programmin?

**Comment by 60bit23** [comment]
you have to use **if... else.. statement** to check prime number.

**Comment by 45bit23** [comment]
**Thank you !**
For making me understand about prime number.
