### ISSUE TITLE
Assignment - 5: Palindrome Checker

### ISSUE THREAD

**Issue by 53bit23** [vtcbca/basic-programming-60bit23#3]
What is the purpose of a palindrome checker program?

**Comment by 60bit23** [comment]
It checks if a word, phrase, or number reads the same backward as forward.

**Comment by 53bit23** [comment]
Can a palindrome contain uppercase and lowercase letters?

**Comment by 60bit23** [comment]
Yes, but to check correctly, the program should ignore case differences.

**Comment by 53bit23** [comment]
How do you handle mixed input like numbers and text in a palindrome checker?

**Comment by 60bit23** [comment]
Convert the input to a string and process it as a single text:

`input_text = str(input_data)`

**Comment by 53bit23** [comment]
an you check for palindrome using recursion?

**Comment by 60bit23** [comment]
Yes, compare the first and last characters, and call the function for the remaining substring

**Comment by 53bit23** [comment]
What is the output if the input is not a palindrome?

**Comment by 60bit23** [comment]
The program should print something like: "This is not a palindrome."
